name: Build and Test

on:
  workflow_run:
    workflows: ["CodeQL Analysis"]
    types:
      - completed

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: List files
        run: ls -R
        
      - name: Use Java 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'
          
      - name: Build with maven
        run: mvn clean install
        working-directory: ./backend/v1

      - name: Run Tests
        run: mvn test
        working-directory: ./backend/v1

      - name: Publish Test Results
        run: mvn surefire-report:report
        working-directory: ./backend/v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_IMAGE }} ./backend/v1

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_IMAGE }}

      - name: Run Docker Container
        run: |
          docker run -d \
            -e MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }} \
            -e MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }} \
            -p 8080:8080 \
            ${{ secrets.DOCKER_IMAGE }}
