name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        run: git clone https://github.com/laurapihamaa/koiratreffit.git

      - name: List directory
        run: ls -R

      - name: Use Java 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'
          
      - name: Build with maven
        run: mvn clean install
        working-directory: ./koiratreffit/backend/v1

      - name: Run Tests
        run: mvn test
