name: Image to docker

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  image-to-docker:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_BACK: ${{ secrets.DOCKER_IMAGE_BACK }}
      DOCKER_IMAGE_FRONT: ${{ secrets.DOCKER_IMAGE_FRONT }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Compose
        run: |
          cd ./backend/v1
          docker-compose build --no-cache

      - name: Push Docker Image
        run: |
          cd ./backend/v1
          docker-compose push
