name: Image to docker

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  image-to-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Compose
        run: docker-compose build

      - name: Push Docker Image
        run: docker-compose push

      - name: Run Docker Container
        run: |
          docker-compose up -d
